# Phase 4 verification — the full pipeline: script -> voice -> talking-head video.
# Prereqs: .\make.ps1 dev  AND  .\make.ps1 models (one-time ~4GB download)
# Usage:   .\scripts\verify_phase4.ps1 -PhotoPath "C:\path\to\your\face.jpg"
param([Parameter(Mandatory=$true)][string]$PhotoPath)

$base = "http://localhost:8000/api/v1"

Write-Host "`n[1/4] SadTalker model server health..." -ForegroundColor Cyan
$h = Invoke-RestMethod "$base/avatar/health"
Write-Host "  status: $($h.status)  checkpoints: $($h.checkpoints_present)"
if (-not $h.checkpoints_present) {
    Write-Host "  Checkpoints missing — run: .\make.ps1 models" -ForegroundColor Red
    exit 1
}

Write-Host "`n[2/4] Synthesize narration audio..." -ForegroundColor Cyan
$ttsBody = @{
    text  = "Hello! I'm an AI avatar generated by avatarforge. My voice comes from Azure Speech, and my face is animated by SadTalker. Pretty cool, right?"
    voice = "professional_female"
} | ConvertTo-Json
$tts = Invoke-RestMethod -Method Post -Uri "$base/tts/synthesize" -ContentType "application/json" -Body $ttsBody
Write-Host "  audio: $($tts.file_id)  ($($tts.audio_duration_sec)s)"

Write-Host "`n[3/4] Generating talking-head video (CPU: expect 2-5 min, be patient)..." -ForegroundColor Cyan
$form = @{
    image         = Get-Item $PhotoPath
    audio_file_id = $tts.file_id
    preprocess    = "crop"
    enhancer      = "false"
}
$sw = [System.Diagnostics.Stopwatch]::StartNew()
$avatar = Invoke-RestMethod -Method Post -Uri "$base/avatar/generate" -Form $form -TimeoutSec 900
$sw.Stop()
Write-Host "  Done in $([int]$sw.Elapsed.TotalSeconds)s"
Write-Host "  Video: $($avatar.video_duration_sec)s  $($avatar.width)x$($avatar.height)  $($avatar.codec)"

Write-Host "`n[4/4] Download + play..." -ForegroundColor Cyan
$out = "$PWD\phase4_avatar_test.mp4"
Invoke-WebRequest "http://localhost:8000$($avatar.video_url)" -OutFile $out
Write-Host "  Saved: $out"
Start-Process $out

Write-Host "`nAudit row:" -ForegroundColor Cyan
docker compose exec -T postgres psql -U avatarforge -d avatarforge -c "SELECT preprocess, enhancer, video_duration_sec, latency_ms, success FROM avatar_usage ORDER BY id DESC LIMIT 3;"
